### ISSUE TITLE
Cannot select a photo

### ISSUE THREAD

**Issue by Congren-Dai** [bpluta/Dogtector#3]
Hi, Mr. Pluta, there is nothing coming up after I select the photo. And after I take a picture, there is always circling and no results. My trained model is trained by this version of YOLOv5 (https://github.com/ultralytics/yolov5/releases/tag/v6.1). I heard that the latest YOLOv5 changed its neural network a little bit. Does that cause no-result problem?

**Comment by Congren-Dai** [comment]
[Archive.zip](https://github.com/bpluta/Dogtector/files/8268742/Archive.zip)
This zip file contains my trained model for detecting lung nodules, so there is only one class that is "nodule". Could you try to run it on your computer? I followed your instructions, and then it could run on my iPhone, but no results. Thanks!!!

**Comment by bpluta** [comment]
Hi @AaronDai1215, indeed there's an issue with processing latest P6 architecture of YOLOv5 models as it contains additional output layer with different dimensional structure which my app does not handle properly. 
```
▿ 4 elements
  ▿ 0 : Optional<MLMultiArray>
    - some : Float32 1 × 3 × 40 × 40 × 6 array
  ▿ 1 : Optional<MLMultiArray>
    - some : Float32 1 × 25200 × 6 array
  ▿ 2 : Optional<MLMultiArray>
    - some : Float32 1 × 3 × 20 × 20 × 6 array
  ▿ 3 : Optional<MLMultiArray>
    - some : Float32 1 × 3 × 80 × 80 × 6 array
```
Bringing support to P6 architecture is definitely something worth working on in the future but I am quite busy lately so please don't expect it anytime soon. For now I would suggest you to train your model on older P5 architecture (that one with 3 output layers instead of 4). Personally, I have trained my model over `yolov5m.pt` weights from v5 release so I assume there should be no issues with the P5 model from the v5 version (https://github.com/ultralytics/yolov5/releases/tag/v5.0)

**Comment by Congren-Dai** [comment]
@bpluta It works!!! Thank you for making such an amazing app. Best regards!!!

**Comment by iscyy** [comment]
> @bpluta It works!!! Thank you for making such an amazing app. Best regards!!!

hi!!Do you have a solution to the reason why 6.1 is not recognized?

**Comment by bpluta** [comment]
@Him-wen Not yet, didn't have time to work on it though yet. But I will be trying to adapt the app to the P6 architecture when I have more time.
