### ISSUE TITLE
add Feature

### ISSUE THREAD

**Issue by iscyy** [bpluta/Dogtector#5]
Excuse me, is it troublesome to add FPS detection and time-consuming UI display?

**Comment by iscyy** [comment]
Does the code of this repo only support models below YOLOv5_v6.0? Are only yolov5n, yolov5s, yolov5m, yolov5l, yolov5x supported? Can other models for improving neural networks be supported?

**Comment by bpluta** [comment]
1. Actually, there is component displaying FPS already. It is not embeded into the production version of the app as it was created for tests only. You can build the test app with the FPS preview by selecting `Dogtector Benchmark` target in Xcode. This target was created for testing purposes so the camera output was replaced with a video for more convenient testing. The video itself is not in the repository because I didn't want to mess with the licenses so you would also need to add a video called `benchmark_example.mp4` as the app will seek for file called like that.

2. Yes, the app has been designed for YOLOv5 P5 architecture only so other networks are not supported. I assume that models trained with earlier versions of YOLOv5 also should work fine with the app but I didn't test them. Bringing support to P6 architecture is in plans but not anytime soon as I have been busy working on other projects lately.

**Comment by iscyy** [comment]
hi Thank you, may I ask what parts of the app need to be changed if I try to update to support the v6.1 architecture? Can you give some general advice? PR if possible

**Comment by iscyy** [comment]
hi!!!, I found that using the official `yolov5s.mlmodel` does not work. I can only convert the `.mlmodel` file through export.py. Can it work? Why is this?

**Comment by bpluta** [comment]
> hi Thank you, may I ask what parts of the app need to be changed if I try to update to support the v6.1 architecture? Can you give some general advice? PR if possible

@Him-wen Basically all of the object decoders needs to be adjusted for the additional layer in the P6 architecture. The most important thing is that it will be necessary to find out how the layer should be decoded because its structure seems to be different from the other three which is the reason why it does not work with my app properly.

> hi!!!, I found that using the official `yolov5s.mlmodel` does not work. I can only convert the `.mlmodel` file through export.py. Can it work? Why is this?

Yes, I have also noticed that there is an issue with the ready CoreML model shared by Ultralytics but I am not sure if it was exported the same way as the `export.py` does. Anyway I didn't notice any issues with any other models exported with the `export.py` script so I assume it is not a problem.

**Comment by iscyy** [comment]
> 

@bpluta Excuse me, if you need to make different model decoding work, which `*.swift` files should be modified?

**Comment by bpluta** [comment]
@Him-wen Basically everything in `Dogtector/ObjectDetector` directory (object decoding strategies and model setup) and `Dogtector/Interactors/DetectorInteractor.swift` (detection interaction interface)
