### ISSUE TITLE
gpu

### ISSUE THREAD

**Issue by iscyy** [bpluta/Dogtector#6]
Devices: iPhone11, A13, iOS15, are the two strategies for object decoding automatically selected to use GPU for work? Debugging on Xcode shows that the GPU usage is 0 and the CPU usage is 130MB

**Comment by bpluta** [comment]
@Him-wen Yes, the strategies are automatically selected choosing the most efficient strategy basing on device capabilities. 

The basic Xcode performance measure tool usually does not display GPU FPS data properly when GPU is used for computing model output rather than rendering. I assume it is more useful for apps created with graphics frameworks like SpriteKit or ARKit thus the zero value is not a problem in this case. More relevant data about GPU usage can be found in Metal System Trace tool in Xcode Instruments with shows that the GPU Performance State is at maximum level during detection. Apart from that, there is Metal debugger which is capturing detection processing data in its capture sessions so the GPU processing works as it should be.
